[features]
seeds = false
[programs.devnet]
mint_nft = "5TiWjhovs8VCHUTiJT3naCF6gWbH4ZE7xpqxGFwkMk2g"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/saumay/.config/solana/id.json"

[scripts]
test-mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-mint.ts"
test-sell = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test-sell.ts"